<?php

$imageTitles = [
    'IMG_4709.jpg' => 'Breathtaking Canyon Sunset',
    'IMG_1834.jpg' => 'Desert Dunes at Sunset',
    '1B1A9657.jpg' => 'Snowy Mountain Range',
    'IMG_0219.jpg' => 'Serene River and Hillside Castle',
    'IMG_0929.jpg' => 'Autumn Mountain Landscape',
    'IMG_2384.jpg' => 'Beachfront House Oasis',
];


$imageDescriptions = [
    'IMG_4709.jpg' => "This stunning image captures a breathtaking view of a large canyon with a river running through it. The sky is an intense blue, dotted with white clouds that stretch across the horizon. In the foreground, we can see a vast ravine filled with jagged rocks and formations that have been carved by years of erosion from the river below. The sun is setting in the distance, casting its golden light on the rugged landscape and creating an incredible contrast between dark shadows and bright highlights. Further down into the canyon, we can see more rock formations as well as patches of green vegetation growing along its sides. This majestic scene is truly awe-inspiring and serves to remind us of nature's beauty and power.",
    'IMG_1834.jpg' => "This image captures a stunning desert landscape, with rolling sand dunes and an expansive sky. The sun is setting in the distance, casting a warm orange glow across the horizon. In the foreground, there are several small bushes scattered throughout the sandy terrain. The sky is a deep blue color that contrasts beautifully against the golden hues of the sand and sunset.\nThe scene has an almost surreal quality to it; one can almost feel as if they have been transported to another world entirely. It's easy to imagine standing atop one of these dunes and taking in this breathtaking view for miles around. This image truly encapsulates what makes deserts so special - their vastness and beauty that can be appreciated from any angle or perspective imaginable.",
    '1B1A9657.jpg' => "This image captures an awe-inspiring spectacle of nature, featuring grand snowy mountain tops shrouded in clouds. The mountain range is expansive, and the viewer is treated to an aerial perspective that accentuates the majesty of the peaks, slopes, and ridges. The snow that blankets the mountains gives them a pristine, ethereal quality, and the clouds add an element of drama to the scene. The sky, a broad canvas of blue, contrasts sharply with the white snow, creating a visually striking image. The photograph captures the raw, rugged beauty of the outdoors, with elements of a glacial landform visible, including what could be a glacier, and a cirque. \nIt also suggests the harsh, cold conditions of the tundra. Furthermore, the image could be of the famous Alps mountain range, renowned for its breathtaking terrain. The picture vividly encapsulates the beauty of winter, showcasing the potent combination of snow, sky, and mountain in a single landscape.",
    'IMG_0219.jpg' => "This is a picturesque view of a serene river against a hill dotted with buildings. The river's calm, blue waters reflect the partially clouded sky above. On the hill, there are green patches of grass and trees scattered among the buildings. One of the buildings stands out with a steeple and a tower, possibly indicating it might be a church or a castle. There are also cars parked in front of this building, suggesting it might be a popular destination for visitors. The overall scene presents a beautiful blend of natural elements and man-made structures, making it a perfect outdoor landscape.",
    'IMG_0929.jpg' => "This is an outdoor scene showcasing the breathtaking beauty of nature. The primary focus is a stunning mountain range, its peaks looming in the background, adding grandeur to the scene. The mountains are interspersed with lush trees, some of which are sporting vibrant red leaves suggestive of autumn. The sky overhead is a clear, striking blue, creating a beautiful contrast against the mountainous landscape. Scattered throughout the scene are groups of trees, adding depth and richness to the image. A person can be seen standing in front of the mountains, possibly enjoying a hiking adventure. The entire scene exudes a sense of wilderness and tranquility, making it a perfect depiction of a highland terrain. The landscape exudes an atmosphere of serenity and is a wonderful representation of the great outdoors.",
    'IMG_2384.jpg' => "This is a tranquil scene of a beachfront house perched on a deck overlooking an expansive body of water. The foreground features a sturdy wooden railing that leads down a staircase, perhaps hinting at a path towards the beach. A sign is affixed on a bench, although its contents are not discernible. Adding some intrigue, there is a rock precariously balanced atop another in the water. The vibrant blue sky is adorned with patches of fluffy clouds, and lush green trees add a splash of color. The house itself is partially obscured, but its rooftop hints at tropical or Caribbean architecture. This seaside resort or town exudes an aura of relaxation, offering an idyllic escape for a beach or nature-themed vacation.",
];
